import type { Metadata } from "next";
import { Sometype_Mono } from "next/font/google";
import "./globals.css";
import PageTransition from "./PageTransition";
import Header from "./Component/Header/Header";
import MainNavbar from "./Component/NavBar/MainNavbar";
import RectangleTransition from "./Component/ui/RectangleTransition";

const SometypeMono = Sometype_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${SometypeMono.variable} antialiased overflow-hidden relative`}
      >
        <RectangleTransition />
        <div className="flex">
          <div className=" hidden lg:flex bg-tertiary w-[285px] h-screen">
            <MainNavbar />
          </div>
          <div className="w-full max-w-[1130px] px-[15px] mx-auto ">
            <Header />
            <PageTransition>
              <div>{children}</div>
            </PageTransition>
          </div>
        </div>
      </body>
    </html>
  );
}
